posts/urls.py
from django.urls import path
from .views import posts_following_users, post_save, like_posts, tweet_detail, comment_save

app_name = 'posts'

urlpatterns = [
    path('', posts_following_users, name='posts-following-users'),
    path('post_save', post_save, name='post-save'),
    path('like/<pk>', like_posts, name='like-post'),
    path('comment', comment_save, name='comment-save'),
    path('<pk>/', tweet_detail.as_view(), name='tweet-detail'),
]

profiles/urls.py
from django.urls import path
from .views import ProfileListView, follow_unfollow_profile, ProfileDetailView, profile_save

app_name = 'profiles'

urlpatterns = [
    path('', ProfileListView.as_view(), name='profile-list-view'),
    path('siwtch_follow/', follow_unfollow_profile, name='follow-unfollow-profile'),
    path('<pk>/', ProfileDetailView.as_view(), name='profile-detail-view'),
    path('profile_save', profile_save, name="profile-save"),
]

twitter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profiles/', include('profiles.urls', namespace='profile')),
    path('home/', include('posts.urls', namespace='posts')),
    path('notification/', include('notify.urls', namespace='notify')),
    path('', include('authentication.urls', namespace='authentication')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # user_name = models.TextField(User)
    profile_image = models.ImageField(upload_to="profile/images", blank=True)
    following = models.ManyToManyField(User, related_name='following', blank=True)
    bio = models.TextField(default="No Bio...")
    notification = models.BooleanField(default=False)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now=True)

    def profile_posts(self):
        return self.post_set.all()

    def __str__(self):
        return str(self.user.username)

    class Meta:
        ordering = ('-created',)

profiles/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from .models import Profile
from django.contrib.auth.models import User

# Create your views here.

class ProfileListView(ListView):
    model = Profile
    template_name = "connect.html"
    context_object_name = 'profiles'

    def get_queryset(self):
        return Profile.objects.all().exclude(user=self.request.user)
        
    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        user = self.request.user
        profile =  Profile.objects.get(user=user)
        context["prof_user"] = profile
        return context
    


def follow_unfollow_profile(request):
    if request.user.is_authenticated is True:
        if request.method == "POST":
            my_profile = Profile.objects.get(user=request.user)
            pk = request.POST.get("profile_pk")
            obj = Profile.objects.get(pk=pk)

            if obj.user in my_profile.following.all():
                my_profile.following.remove(obj.user)

            else:
                my_profile.following.add(obj.user)
            
            return redirect(request.META.get('HTTP_REFERER'))

        return redirect('profiles:profile-list-view')
    
    else:
        return redirect("/")

class ProfileDetailView(DetailView):

    model = Profile
    template_name = 'profile.html'
    
    def get_object(self, **kwargs):

        pk = self.kwargs.get('pk')
        view_profile = Profile.objects.get(pk=pk)
        return view_profile
        # return super().get_object()


    
    def get_context_data(self, **kwargs):
    
        context = super().get_context_data(**kwargs)
        user = self.request.user
        profile =  Profile.objects.get(user=user)
        context["prof_user"] = profile
        return context



def profile_save(request):
    if request.user.is_authenticated is True:
        if request.method == 'POST':
            name = request.POST.get('name')
            bio = request.POST.get('bio')
            img = request.POST.get('imgInp') 
            user = User.objects.get(username=request.user)
            profile = Profile.objects.get(user=request.user)
            print(name, bio, img)

            try:
                img_file = request.FILES['imgInp']
                profile.profile_image = img_file
                # profile.save()
            except Exception:
                pass
            if name:
                user.username = name
                user.save()
            if bio:
                # profile = Profile.objects.get(user=request.user)
                profile.bio = bio
            else:
                pass
            profile.save()
            print(name, bio, img)
        return redirect(request.META.get('HTTP_REFERER'))

    else:
        return redirect("/")
        

profiles/templates/connect.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Connect
{% endblock title %}
{% block style %}
<style>
svg:hover{
    background-color: #e6ecf0;
}
.mid_head{
    font-size: larger;
    font-weight: bolder;
}
button:focus{
   outline:none;
}
.follow{
    float: right;
    width: 100px;
    height: 40px;
    float: right;
    color: #007bff; 
    background-color: transparent;
    font-size: large;
    font-weight: bolder;
    border-color: #007bff;
    display: block;
    border-radius: 50px;
}
.following{
    float: right;
    width: 100px;
    height: 40px;
    float: right;
    color: white; 
    background-color: #007bff;
    font-size: large;
    font-weight: bolder;
    border-color: #007bff;
    display: block;
    border-radius: 50px;
}
.following:hover{
    background-color: red;
    border-color: red;
}
.following:hover span {display:none}
.following:hover:before{content:"Unfollow"}
.follow:hover{
    outline: none;
    background-color: #cce8fa;
}
.sub_follow .name{
    margin-left: 20px;
    text-align: center;
    font-weight: bold;
    font-size: 20px;
}
.sub_follow .user_name{
    margin-left: 20px;
    text-align: center;
    color: #657786;
    font-weight: lighter;
    font-size: medium;
}
a{
    color: black;
    text-decoration: none;
}
a:hover{
    text-decoration: none;
    color: black;
}
.sub_follow:hover{
    background-color: #f2f1f1;
    border-radius: 50px;
}
</style>
{% endblock style %}

{% block head %}
<a href="#">
<svg onclick="goBack()" style="float:left" viewBox="0 0 24 24" class="r-13gxpu9 r-4qtqp9 r-yyyyoo r-1q142lx r-50lct3 r-dnmrzs r-bnwqim r-1plcrui r-lrvibr r-1srniue"><g><path d="M20 11H7.414l4.293-4.293c.39-.39.39-1.023 0-1.414s-1.023-.39-1.414 0l-6 6c-.39.39-.39 1.023 0 1.414l6 6c.195.195.45.293.707.293s.512-.098.707-.293c.39-.39.39-1.023 0-1.414L7.414 13H20c.553 0 1-.447 1-1s-.447-1-1-1z"></path></g></svg>
</a>
<span class="mx-4 top_head">Connect</span>
{% endblock head %}

{% block main_post %}
{% endblock main_post %}

{% block gap %}
<span class="mid_head">
You may be interested in
</span> 
{% endblock gap %}

{% block mid_body %}
<div class="mx-4 my-4 who_follow">
{% for profile in profiles %}

                <a href={% url 'profiles:profile-detail-view' profile.pk%}>
                <form method="POST" action="{% url 'profiles:follow-unfollow-profile' %}">
                {% csrf_token %}
                <div class="row ">
                    <div class="col  sub_follow" >
                        <span class="name">
                            <input type="hidden" name='profile_pk' value={{profile.pk}}>
                            {% if profile.profile_image %}
                            <img src="/media/{{profile.profile_image}}" alt="Avatar" style="height: 50px; width: 50px; float: left; border-radius: 100px;">
                            {% else %}
                            <img src="{% static 'img/prof.jpg' %}" alt="Avatar" style="height: 50px; width: 50px; float: left; border-radius: 100px;">
                            {% endif %}
                            {% if profile.user in prof_user.following.all %}
                            <button class="following my-2" type="submit"><span>Following</span></button>
                            {% else %}
                            <button class="follow my-2" type="submit">Follow</button>
                            {% endif %}
                            {{profile.user}}
                        </span>
                        <br>
                        <span class="user_name">
                            @{{profile.user}}
                        </span>
                    </div>
                </div>
                <hr>
            </form>
                </a>
{% endfor %}  
            </div>
{% endblock mid_body %}